# Generated by Django 4.0.5 on 2022-07-03 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.TextField()),
                ('person', models.CharField(max_length=50)),
                ('schedule_status', models.CharField(choices=[('Preparation', 'Preparation'), ('Done', 'Done'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], max_length=50)),
            ],
        ),
    ]
