# Generated by Django 4.0.6 on 2022-07-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_professional', models.CharField(max_length=50)),
                ('consultant_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('type_of_license', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('No License', 'No License')], max_length=50)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LawyerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_professional', models.CharField(max_length=50)),
                ('lawyer_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
